### PR TITLE
Review

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
I have these change suggestions. Detailed descriptions can be found in the commit messages.

This is mainly a maintenance update with no functional changes.

If this is too many changes for you to review, let me know and I'll do a smaller PR :slightly_smiling_face:

### CODE REVIEW

**Comment by KristjanESPERANTO** [comment]
@sdetweil Did you noticed this PR? :slightly_smiling_face:

**Comment by sdetweil** [comment]
I did miss it..   note that I don't own the module, just added some to the doc. and code.. 
so I don't feel responsible for updating all this..  (and I HATE camelCase) 

this points out (again) that I need to fix the upgrade script cause it checks for package,json.. which causes an npm install..
which is incorrect now that we have documentation only package.json files..

**Comment by KristjanESPERANTO** [comment]
Thanks for merging! :slightly_smiling_face: 

> so I don't feel responsible ...

Since you wrote "`i'm ready to be maintainer`" in [PR 72](https://github.com/edward-shen/MMM-pages/issues/72), I thought you were. If not, should we mark the module as abandoned in the module list?

> which is incorrect now that we have documentation only package.json files.

Just nitpicking: There were already modules that only had devDependencies and no dependecies, so it was already incorrect before.

**Comment by edward-shen** [comment]
@KristjanESPERANTO

My module is not abandoned, it's just mature and doesn't really need any updates. I'm still responsive to PRs, it's just no one made any recently (except for a merge attempt with this repo).

In the future, before declaring anything "dead" or "abandoned" and switching the MagicMirror wiki to a different fork, I'd suggest asking the maintainer for an update first and waiting a bit. They just might be on vacation :)

This is also a request to switch back the wiki to point to my repo, or at least have both present.

**Comment by KristjanESPERANTO** [comment]
@edward-shen Sorry for any disturbances. But all actions were taken with good intentions and good reasons.

> I'm still responsive to PRs

Great! Your previous text in the README led us to believe otherwise.

> My module ... doesn't really need any updates.

Even when a module is functionally mature, there are almost always reasons to work on details. Be it because a small feature is missing, the development process (like lintering) is not solved optimally or there are new external requirements (such as the new module list or any breaking changes in the dependencies).

But I think, we can get it sorted out somehow. I've seen the failed attempts to integrate Sam's fork into yours. It's desirable not to have two versions of the module in the module list, so I'll also try some small PRs. I'm not sure I can follow all the changes in Sam's fork, so I'll limit myself to the ones I understand. My interim goal is to get to a state where the differences between Sam's fork and your repository are much more clear.

If that works, we can replace sam's fork in the list with yours again. If not, we'll add yours back in and have two versions, but then we should somehow make it clear to the users what the differences are.

@sdetweil Would that be okay for you?

**Comment by sdetweil** [comment]
Do what you will. Good intentions is true

**Pull request merged**
